# 运行模式(debug:调试,test:测试,release:正式)
run_model = "test"

# swagger文档目录
swagger = ""

# 数据存储(支持: gorm)
store = "gorm"

# 日志配置
[log]
# 日志级别(1:fatal,2:error,3:warn,4:info,5:debug)
level = 5
# 日志格式(支持: stdout/stderr/file)
output = "stdout"
# 指定日志输出的文件路径
output_file = "data/gindemo.log"
# 是否启动日志钩子(支持: gorm)
enable_hook = false
# 写入钩子的最大工作线程数量
hook_max_thread = 1
# 写入钩子的最大缓冲区数量
hook_max_buffer = 512

# 日志gorm钩子配置
[log_gorm_hook]
# 数据库类型(目前支持的数据库类型: mysql/sqlite3/postgres)
db_type = "sqlite3"
# 设置连接可以重用的最长连接时间(单位： 秒)
max_lifetime = 7200
# 设置数据库最大打开连接数
max_open_conns = 1
# 设置空闲连接池中的最大连接数
max_idle_conns = 1
# 数据库表名
table = "g_logger"

# 跨域请求
[cors]
# 是否启用
enable = false
# 允许跨域请求的域名列表(*表示全部允许)
allow_origins = ["*"]
# 允许跨域请求的请求方式列表
allow_methods = ["GET","POST","PUT","DELETE","PATCH"]
# 允许客户端与跨域请求一起使用的非简单标头的列表
allow_headers = []
allow_credentials = true
max_age = 7200

# gorm配置
[gorm]
# 是否开启调试模式
debug = true
# 数据库类型
db_type = "sqlite3"
# 设置连接可以重用的最长时间
max_lifetime = 7200
# 设置数据库的最大打开连接数
max_open_conns = 150
# 设置空闲连接池中的最大连接数
max_idle_conns = 50
# 数据库表名前缀
table_prefix = "g_"

# mysql数据库配置
[mysql]
host = "127.0.0.1"
port = 3306
user = "root"
password = "123456"
db_name = "gindemo"
paraneters = "charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"

# postgres数据库配置
[postgres]
# 连接地址
host = "127.0.0.1"
port = 5432
user = "root"
password = "123456"
db_name = "gindemo"

[sqlite3]
path = "data/gindemo.db"


